default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: authentication_api_development

test:
  <<: *default
  database: authentication_api_test

production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>
